import mongoose from "mongoose";

const DocenteUnidade = new mongoose.Schema({
    tipoDeRegistro: { type: String, required: false },
    codigoDeEscolaInep: { type: String, required: false },
    codigoDaPessoaFisicaNoSistemaProprio: { type: String, required: false },
    identificacaoUnicaInep: { type: String, required: false },
    codigoDaTurmaNaEntidadeEscola: { type: String, required: false },
    codigoDaTurmaNoINEP: { type: String, required: false },
    funcaoQueExerceNaEscolaTurma: { type: String, required: false },
    situacaoFuncionalregimeDeContratacaotipoDeVinculo: { type: String, required: false },
    codigo1: { type: String, required: false },
    codigo2: { type: String, required: false },
    codigo3: { type: String, required: false },
    codigo4: { type: String, required: false },
    codigo5: { type: String, required: false },
    codigo6: { type: String, required: false },
    codigo7: { type: String, required: false },
    codigo8: { type: String, required: false },
    codigo9: { type: String, required: false },
    codigo10: { type: String, required: false },
    codigo11: { type: String, required: false },
    codigo12: { type: String, required: false },
    codigo13: { type: String, required: false },
    codigo14: { type: String, required: false },
    codigo15: { type: String, required: false },
    codigo16: { type: String, required: false },
    codigo17: { type: String, required: false },
    codigo18: { type: String, required: false },
    codigo19: { type: String, required: false },
    codigo20: { type: String, required: false },
    codigo21: { type: String, required: false },
    codigo22: { type: String, required: false },
    codigo23: { type: String, required: false },
    codigo24: { type: String, required: false },
    codigo25: { type: String, required: false },
    eletivas: { type: String, required: false },
    libras: { type: String, required: false },
    linguaIndigena: { type: String, required: false },
    linguaLiteraturaEstrangeiraEspanhol: { type: String, required: false },
    linguaLiteraturaEstrangeiraFrances: { type: String, required: false },
    linguaLiteraturaEstrangeiraOutra: { type: String, required: false },
    projetoDeVida: { type: String, required: false },
    trilhasDeAprofundamentoaprendizagens: { type: String, required: false },
    outrasUnidadesCurricularesObrigatorias: { type: String, required: false },
})

export default mongoose.model('DocenteUnidade', DocenteUnidade);
