import mongoose from "mongoose";


const Unidade = new mongoose.Schema({
    tipoDeRegistro: { type: String, required: false },
    codigoDeEscolaInep: { type: Number, required: false },
    situacaoDeFuncionamento: { type: Number, required: false },
    dataDeInicioDoAnoLetivo: { type: Date, required: false },
    dataDeTerminoDoAnoLetivo: { type: Date, required: false },
    nomeDaEscola: { type: String, required: false },
    cEP: { type: Number, required: false },
    municipio: { type: Number, required: false },
    distrito: { type: Number, required: false },
    endereco: { type: String, required: false },
    numero: { type: String, required: false },
    complemento: { type: String, required: false },
    bairro: { type: String, required: false },
    dDD: { type: Number, required: false },
    telefone: { type: Number, required: false },
    outroTelefoneDeContato: { type: Number, required: false },
    enderecoEletronicoEmailDaEscola: { type: String, required: false },
    codigoDoOrgaoRegionalDeEnsino: { type: String, required: false },
    localizacaoZonaDaEscola: { type: Number, required: false },
    localizacaoDiferenciadaDaEscola: { type: Number, required: false },
    dependenciaAdministrativa: { type: Number, required: false },
    secretariaDeEducacaoMinisterioDaEducacao: { type: Number, required: false },
    secretariaDeSegurancaPublicaForcasArmadasMilitar: { type: Number, required: false },
    secretariaDaSaudeMinisterioDaSaude: { type: Number, required: false },
    outroOrgaoDaAdministracaoPublica: { type: Number, required: false },
    empresaGruposEmpresariaisDoSetorPrivadoOuPessoaFisica: { type: Number, required: false },
    sindicatosDeTrabalhadoresOuPatronaisAssociacoesCooperativas: { type: Number, required: false },
    organizacaoNaoGovernamentalONGNacionalOuInternacional: { type: Number, required: false },
    instituicaoSemFinsLucrativos: { type: Number, required: false },
    sistemaSSesiSenaiSescOutros: { type: Number, required: false },
    organizacaoDaSociedadeCivilDeInteressePublicoOscip: { type: Number, required: false },
    categoriaDaEscolaPrivada: { type: Number, required: false },
    secretariaEstadual: { type: Number, required: false },
    secretariaMunicipal: { type: Number, required: false },
    naoPossuiParceriaOuConvenio: { type: Number, required: false },
    termoDeColaboracaoLeiN130192014: { type: Number, required: false },
    termoDeFomentoLeiN130192014: { type: Number, required: false },
    acordoDeCooperacaoLeiN130192014: { type: Number, required: false },
    contratoDePrestacaoDeServico: { type: Number, required: false },
    termoDeCooperacaoTecnicaEFinanceira: { type: Number, required: false },
    contratoDeConsorcioPublicoConvenioDeCooperacao: { type: Number, required: false },
    termoDeColaboracaoLeiN130192014Mun: { type: Number, required: false },
    termoDeFomentoLeiN130192014Mun: { type: Number, required: false },
    acordoDeCooperacaoLeiN130192014Mun: { type: Number, required: false },
    contratoDePrestacaoDeServicoMun: { type: Number, required: false },
    termoDeCooperacaoTecnicaEFinanceiraMun: { type: Number, required: false },
    contratoDeConsorcioPublicoConvenioDeCooperacaoMun: { type: Number, required: false },
    cNPJDaMantenedoraPrincipalDaEscolaPrivada: { type: String, required: false },
    numeroDoCNPJDaEscolaPrivada: { type: String, required: false },
    regulamentacaoautorizacaoNoConselhoOuOrgaoMunicipalEstadualOuFederalDeEducacao: { type: Number, required: false },
    federal: { type: Number, required: false },
    estadual: { type: Number, required: false },
    municipal: { type: Number, required: false },
    unidadeVinculadaAEscolaDeEducacaoBasicaOuUnidadeOfertanteDeEducacaoSuperior: { type: Number, required: false },
    codigoDaEscolaSede: { type: Number, required: false },
    codigoDaIES: { type: Number, required: false },
})

export default mongoose.model('Unidade', Unidade);